### PR TITLE
Add support for Markdown chapters

### PR DESCRIPTION
**Pull request by JohnAZoidberg**

### CODE REVIEW

**Comment by lschuermann** [comment]
This PR seems to be very helpful, especially with writing error-free LaTeX.
Can you also embed complex structures like tikz graphics or other environments in the markdown source? Is there some marker to tell `pandoc` to not touch this part of the source?

Also, this should be documented in the repo's `README.md` so others know that they can write their content in markdown.

**Comment by JohnAZoidberg** [comment]
Sure you can embed LaTeX. Take a look at the example.

Yeah, good idea. I'll add it to the readme.

**Comment by lschuermann** [comment]
I'm fine with this being merged. However, if there are any issues we are not responsible for all things `pandoc`-related. That should be stated in the readme.

**Review by lschuermann — APPROVED** [review]
Looks good to me.

**Comment by lschuermann** [comment]
Actually, this seems to break a lot of people's setups. Related to #2, people don't want to use Nix and also don't want to install pandoc.

I'm thinking about at least removing the import of the markdown file in the template. How much of an issue would it be, if you'd manually generate the `.tex` from the `.md` before requesting a pull? I'd be fine even if the Markdown source was left in the repo.

**Comment by JohnAZoidberg** [comment]
Ok, I'll do it on my own fork.

**Pull request merged**
