### PR TITLE
Add glossaries-extra package for abbreviations

### PR DESCRIPTION
**Pull request by lschuermann**
We should provide a unified solution for having abbreviations, acronyms and glossary entries in the book.

The already merged graphdb-chapter should be changed to use this package.

### CODE REVIEW

**Comment by danielrutz** [comment]
LGTM.

Should we edit the already merged chapter ourselves or shall we ask the authors to do that?

**Comment by lschuermann** [comment]
This should probably be done in this PR. In new PRs we can then look out / at least tell the respective authors to not have any global labels or manual abbreviations in their document.

**Review by danielrutz — APPROVED** [review]

**Comment by lschuermann** [comment]
I've changed the manually defined in-line acronyms and abbreviations from the Neo4j chapter to use the glossaries-package.

@ThoreKr, @Oswaldbob, @johannaSommer Please verify that I didn't accidentally change any content or otherwise broke your chapter. I will assume that it is fine, if I don't hear back from you until tomorrow. (We need this merged fast)

**Review by Oswaldbob — APPROVED** [review]
Looks good, thank you very much!

**Pull request merged**
